### ISSUE TITLE
Scoreboard badly scaled

### ISSUE THREAD

**Issue by Ch0wW** [Ch0wW/odamex#1]
A.K.A. : unless using a value +/-0.25, the scoreboard isn't scaled.

**Comment by AlexMax** [comment]
I am the one who implemented the scoreboard and I actually agree wholeheartedly - the current state of scaling in Odamex is less than ideal.

Zandronum has an amazing "Text Scaling" submenu, which allows me to specify a virtual resolution that I want text to be scaled to, along with the ability to anchor text to the actual edge of the screen or to the edge of a virtual 4:3 screen.  It makes intuitive sense, and I'd love to see something like that in Odamex.
