### ISSUE TITLE
Discord integration with Odamex

### ISSUE THREAD

**Issue by Ch0wW** [Ch0wW/odamex#24]
Discord has for a while an API (discord-rpc) for Game Integration. So let's add it too !

**Comment by Ch0wW** [comment]
Please check branch DISCORD to see how it's implemented.

Make sure you manually link your discord-rpc library (made for VS++ 2018 x86 atm) and its include folder.

**Comment by MenonPenguin89420** [comment]
It doesn't work with Mac OS. Is it intended to?

**Comment by Ch0wW** [comment]
It is unintended, but that feature will be scrapped anyway.
