### ISSUE TITLE
Spectator code enhancements

### ISSUE THREAD

**Issue by Ch0wW** [Ch0wW/odamex#3]
FROM PRODAMEX changelog: 

- Added cl_spectator_freelook_force to force freelook as a spectator even if the server doesn't allow it.
- Added cl_spectator_flybob for controlling the flying bobbing as a SPECTATOR.
- Added cl_spectator_allow_teleport. Seems understandable.

**Comment by capodecima** [comment]
Go for it! :dancing_men:

**Comment by Ch0wW** [comment]
Update commited, won't add those 2 features:

> - Added cl_spectator_show_usetojoin. Shows or not the joining possibilities of a spectator.
> - Crosshair is drawn as a spectator.

The main reason is there is no use at all for now. A Shoutcasting HUD could be even more interesting in the near future.

However, I'll force flymove once you enter a game or as a spectator before closing this ticket.

**Comment by Ch0wW** [comment]
https://github.com/Ch0wW/odamex/commit/e714f570101f136e3915bf69f658f8200806c139 ends this ticket! Thanks Capodecima!

**Comment by Ch0wW** [comment]
I managed to make the client crash whenever monsters entered a teleporter.

**Comment by AlexMax** [comment]
How many of these additional cvars does Odamex actually need?

Don't get me wrong, I like the additional functionality, but I'm not quite sure we should be adding additional cvars to go with it - I much prefer sensible defaults to cvar creep.

**Comment by Ch0wW** [comment]
Well, it depends, those liking to get complete control of their spectating mode after all (I honestly do, and several others aswell, as they were from Zd/Zand)

Also, CVARs to customize deeply your client is something modern Doom clients are lacking, hence that current fork to make everyone happy for now. At least that could attract a little more people to see that odamex is definitely a good port with customisation as a key, but I could get wrong (despite having such discussion a while ago) since it would probably break the main goals. 

(also, lots of rebase errors to keep it in sync with the latest official odamex commits, wow I sucked hard in this one...)

**Comment by capodecima** [comment]
> AlexMax commented 2 days ago
How many of these additional cvars does Odamex actually need?

I dont see any problem having a lot cvars. Basically the more you have option how to set your client the better. You can be suprised how some people are nitpicking in their configs and like to many options to work with. Probably good example is QL. you can custome and set up almost everything you can imagine in game, and its all good. I dont think this port can ever turn to some hybrid NS port or something,  Honestly this feature or any others from Ch0wW are reasonable for me...

**Comment by Ch0wW** [comment]
Changes have been accepted to development branch, some slight modifications have also been done. Closing !
